//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleAcessoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class PessoaDto : object
    {
        
        private string CodigoField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
    public partial class BusinessFault : object
    {
        
        private int ErrorNumberField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumber
        {
            get
            {
                return this.ErrorNumberField;
            }
            set
            {
                this.ErrorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
    public partial class GeneralFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class SistemaOutputDto : ControleAcessoService.SistemaDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.SistemaOutputDto))]
    public partial class SistemaDto : object
    {
        
        private string CodigoField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string DescricaoField;
        
        private string DescricaoStatusField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        private string SiglaField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatus
        {
            get
            {
                return this.DescricaoStatusField;
            }
            set
            {
                this.DescricaoStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigla
        {
            get
            {
                return this.SiglaField;
            }
            set
            {
                this.SiglaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DominioDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class DominioDto : object
    {
        
        private string CodigoDominioField;
        
        private string CodigoSubDominioField;
        
        private string DescricaoDominioField;
        
        private string DescricaoSubDominioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDominio
        {
            get
            {
                return this.CodigoDominioField;
            }
            set
            {
                this.CodigoDominioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSubDominio
        {
            get
            {
                return this.CodigoSubDominioField;
            }
            set
            {
                this.CodigoSubDominioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoDominio
        {
            get
            {
                return this.DescricaoDominioField;
            }
            set
            {
                this.DescricaoDominioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoSubDominio
        {
            get
            {
                return this.DescricaoSubDominioField;
            }
            set
            {
                this.DescricaoSubDominioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class PerfilOutputDto : ControleAcessoService.PerfilDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.PerfilOutputDto))]
    public partial class PerfilDto : object
    {
        
        private string CodigoField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string DescricaoField;
        
        private string DescricaoStatusField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatus
        {
            get
            {
                return this.DescricaoStatusField;
            }
            set
            {
                this.DescricaoStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcaoOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class AcaoOutputDto : ControleAcessoService.AcaoDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcaoDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.AcaoOutputDto))]
    public partial class AcaoDto : object
    {
        
        private string CodigoAcaoField;
        
        private string CodigoModuloField;
        
        private string CodigoSistemaField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string DescricaoAcaoField;
        
        private string DescricaoAliasField;
        
        private string DescricaoFuncaoField;
        
        private string DescricaoStatusField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAcao
        {
            get
            {
                return this.CodigoAcaoField;
            }
            set
            {
                this.CodigoAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModulo
        {
            get
            {
                return this.CodigoModuloField;
            }
            set
            {
                this.CodigoModuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSistema
        {
            get
            {
                return this.CodigoSistemaField;
            }
            set
            {
                this.CodigoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoAcao
        {
            get
            {
                return this.DescricaoAcaoField;
            }
            set
            {
                this.DescricaoAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoAlias
        {
            get
            {
                return this.DescricaoAliasField;
            }
            set
            {
                this.DescricaoAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFuncao
        {
            get
            {
                return this.DescricaoFuncaoField;
            }
            set
            {
                this.DescricaoFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatus
        {
            get
            {
                return this.DescricaoStatusField;
            }
            set
            {
                this.DescricaoStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuloOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class ModuloOutputDto : ControleAcessoService.ModuloDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuloDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.ModuloOutputDto))]
    public partial class ModuloDto : object
    {
        
        private string CodigoModuloField;
        
        private string CodigoModuloAnteriorField;
        
        private string CodigoSistemaField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string DescricaoField;
        
        private string DescricaoFuncaoField;
        
        private string DescricaoIconeMenuField;
        
        private string DescricaoMensagemField;
        
        private string DescricaoSistemaField;
        
        private string DescricaoStatusField;
        
        private string DescricaoTeclaField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        private int OrdemApresentacaoField;
        
        private string StatusField;
        
        private string TipoField;
        
        private System.Collections.Generic.List<ControleAcessoService.AcaoOutputDto> _AcoesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModulo
        {
            get
            {
                return this.CodigoModuloField;
            }
            set
            {
                this.CodigoModuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModuloAnterior
        {
            get
            {
                return this.CodigoModuloAnteriorField;
            }
            set
            {
                this.CodigoModuloAnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSistema
        {
            get
            {
                return this.CodigoSistemaField;
            }
            set
            {
                this.CodigoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFuncao
        {
            get
            {
                return this.DescricaoFuncaoField;
            }
            set
            {
                this.DescricaoFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoIconeMenu
        {
            get
            {
                return this.DescricaoIconeMenuField;
            }
            set
            {
                this.DescricaoIconeMenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoMensagem
        {
            get
            {
                return this.DescricaoMensagemField;
            }
            set
            {
                this.DescricaoMensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoSistema
        {
            get
            {
                return this.DescricaoSistemaField;
            }
            set
            {
                this.DescricaoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatus
        {
            get
            {
                return this.DescricaoStatusField;
            }
            set
            {
                this.DescricaoStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoTecla
        {
            get
            {
                return this.DescricaoTeclaField;
            }
            set
            {
                this.DescricaoTeclaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdemApresentacao
        {
            get
            {
                return this.OrdemApresentacaoField;
            }
            set
            {
                this.OrdemApresentacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ControleAcessoService.AcaoOutputDto> _Acoes
        {
            get
            {
                return this._AcoesField;
            }
            set
            {
                this._AcoesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class UsuarioOutputDto : ControleAcessoService.UsuarioDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.UsuarioOutputDto))]
    public partial class UsuarioDto : object
    {
        
        private string CodigoField;
        
        private string CodigoPerfilField;
        
        private string CodigoPessoaField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataExpiraField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string DescricaoPerfilField;
        
        private string DescricaoStatusField;
        
        private System.Nullable<int> DiasExpiraField;
        
        private string EmailField;
        
        private string IndicacaoEspecialField;
        
        private int LimiteTentativasField;
        
        private string LoginField;
        
        private string NomeField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        private string SenhaField;
        
        private string StatusField;
        
        private string TipoEntidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPessoa
        {
            get
            {
                return this.CodigoPessoaField;
            }
            set
            {
                this.CodigoPessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataExpira
        {
            get
            {
                return this.DataExpiraField;
            }
            set
            {
                this.DataExpiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoPerfil
        {
            get
            {
                return this.DescricaoPerfilField;
            }
            set
            {
                this.DescricaoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoStatus
        {
            get
            {
                return this.DescricaoStatusField;
            }
            set
            {
                this.DescricaoStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiasExpira
        {
            get
            {
                return this.DiasExpiraField;
            }
            set
            {
                this.DiasExpiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicacaoEspecial
        {
            get
            {
                return this.IndicacaoEspecialField;
            }
            set
            {
                this.IndicacaoEspecialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteTentativas
        {
            get
            {
                return this.LimiteTentativasField;
            }
            set
            {
                this.LimiteTentativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEntidade
        {
            get
            {
                return this.TipoEntidadeField;
            }
            set
            {
                this.TipoEntidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilAcaoOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class PerfilAcaoOutputDto : ControleAcessoService.PerfilAcaoDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilAcaoDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.PerfilAcaoOutputDto))]
    public partial class PerfilAcaoDto : object
    {
        
        private string AcaoDescricaoAcaoField;
        
        private string AcaoDescricaoAliasField;
        
        private string AcaoDescricaoFuncaoField;
        
        private string CodigoAcaoField;
        
        private string CodigoModuloField;
        
        private string CodigoPerfilField;
        
        private string CodigoSistemaField;
        
        private System.Nullable<System.DateTime> DataAlteracaoField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string NomeUsuarioAlteracaoField;
        
        private string NomeUsuarioInclusaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcaoDescricaoAcao
        {
            get
            {
                return this.AcaoDescricaoAcaoField;
            }
            set
            {
                this.AcaoDescricaoAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcaoDescricaoAlias
        {
            get
            {
                return this.AcaoDescricaoAliasField;
            }
            set
            {
                this.AcaoDescricaoAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcaoDescricaoFuncao
        {
            get
            {
                return this.AcaoDescricaoFuncaoField;
            }
            set
            {
                this.AcaoDescricaoFuncaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAcao
        {
            get
            {
                return this.CodigoAcaoField;
            }
            set
            {
                this.CodigoAcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModulo
        {
            get
            {
                return this.CodigoModuloField;
            }
            set
            {
                this.CodigoModuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSistema
        {
            get
            {
                return this.CodigoSistemaField;
            }
            set
            {
                this.CodigoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return this.DataAlteracaoField;
            }
            set
            {
                this.DataAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioAlteracao
        {
            get
            {
                return this.NomeUsuarioAlteracaoField;
            }
            set
            {
                this.NomeUsuarioAlteracaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilModuloOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    public partial class PerfilModuloOutputDto : ControleAcessoService.PerfilModuloDto
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilModuloDto", Namespace="http://schemas.datacontract.org/2004/07/Coreon.ControleAcesso.Contract")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ControleAcessoService.PerfilModuloOutputDto))]
    public partial class PerfilModuloDto : object
    {
        
        private string CodigoModuloField;
        
        private string CodigoPerfilField;
        
        private string CodigoSistemaField;
        
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        private string NomeUsuarioInclusaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoModulo
        {
            get
            {
                return this.CodigoModuloField;
            }
            set
            {
                this.CodigoModuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPerfil
        {
            get
            {
                return this.CodigoPerfilField;
            }
            set
            {
                this.CodigoPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSistema
        {
            get
            {
                return this.CodigoSistemaField;
            }
            set
            {
                this.CodigoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return this.DataInclusaoField;
            }
            set
            {
                this.DataInclusaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuarioInclusao
        {
            get
            {
                return this.NomeUsuarioInclusaoField;
            }
            set
            {
                this.NomeUsuarioInclusaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControleAcessoService.IControleAcessoService")]
    public interface IControleAcessoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPessoas", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPessoasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPessoasBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPessoasGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PessoaDto>> ListarPessoasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarSistemas", ReplyAction="http://tempuri.org/IControleAcessoService/ListarSistemasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarSistemasBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarSistemasGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.SistemaOutputDto>> ListarSistemasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarSistemaPorCodigo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarSistemaPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarSistemaPorCodigoBusinessFaultFaul" +
            "t", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarSistemaPorCodigoGeneralFaultFault" +
            "", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.SistemaOutputDto> ListarSistemaPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarSistema", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarSistemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarSistemaBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarSistemaGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarSistemaAsync(ControleAcessoService.SistemaDto sistemaDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirSistema", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirSistemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirSistemaBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirSistemaGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirSistemaAsync(ControleAcessoService.SistemaDto sistemaDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarDominio", ReplyAction="http://tempuri.org/IControleAcessoService/ListarDominioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarDominioBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarDominioGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.DominioDto>> ListarDominioAsync(string dominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPerfis", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPerfisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilOutputDto>> ListarPerfisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPerfilPorCodigo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPerfilPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfilPorCodigoBusinessFaultFault" +
            "", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfilPorCodigoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.PerfilOutputDto> ListarPerfilPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarPerfil", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarPerfilAsync(ControleAcessoService.PerfilDto perfilDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirPerfil", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirPerfilAsync(ControleAcessoService.PerfilDto perfilDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModulo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloBusin" +
            "essFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloGener" +
            "alFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.AcaoOutputDto>> ListarPorCodigoSistemaCodigoModuloAsync(string codigoSistema, string codigoModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloCodig" +
            "oAcao", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloCodig" +
            "oAcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloCodig" +
            "oAcaoBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPorCodigoSistemaCodigoModuloCodig" +
            "oAcaoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.AcaoOutputDto> ListarPorCodigoSistemaCodigoModuloCodigoAcaoAsync(string codigoSistema, string codigoModulo, string codigoAcao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarAcao", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarAcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarAcaoBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarAcaoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarAcaoAsync(ControleAcessoService.AcaoDto acaoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirAcao", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirAcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirAcaoBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirAcaoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirAcaoAsync(ControleAcessoService.AcaoDto acaoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarModulos", ReplyAction="http://tempuri.org/IControleAcessoService/ListarModulosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarModulosBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarModulosGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModulosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarModuloPorCodigo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarModuloPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarModuloPorCodigoBusinessFaultFault" +
            "", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarModuloPorCodigoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.ModuloOutputDto> ListarModuloPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarModuloPorModuloAnterior", ReplyAction="http://tempuri.org/IControleAcessoService/ListarModuloPorModuloAnteriorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarModuloPorModuloAnteriorBusinessFa" +
            "ultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarModuloPorModuloAnteriorGeneralFau" +
            "ltFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModuloPorModuloAnteriorAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarModulosPorPerfil", ReplyAction="http://tempuri.org/IControleAcessoService/ListarModulosPorPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarModulosPorPerfilBusinessFaultFaul" +
            "t", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarModulosPorPerfilGeneralFaultFault" +
            "", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModulosPorPerfilAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarModulo", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarModuloBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarModuloGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarModuloAsync(ControleAcessoService.ModuloDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirModulo", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirModuloBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirModuloGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirModuloAsync(ControleAcessoService.ModuloDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarUsuarios", ReplyAction="http://tempuri.org/IControleAcessoService/ListarUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuariosBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuariosGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.UsuarioOutputDto>> ListarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorCodigo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarUsuarioPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorCodigoBusinessFaultFaul" +
            "t", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorCodigoGeneralFaultFault" +
            "", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorLogin", ReplyAction="http://tempuri.org/IControleAcessoService/ListarUsuarioPorLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorLoginBusinessFaultFault" +
            "", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorLoginGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorEmail", ReplyAction="http://tempuri.org/IControleAcessoService/ListarUsuarioPorEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorEmailBusinessFaultFault" +
            "", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarUsuarioPorEmailGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarUsuario", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarUsuarioBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarUsuarioGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarUsuarioAsync(ControleAcessoService.UsuarioDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirUsuario", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirUsuarioBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirUsuarioGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirUsuarioAsync(ControleAcessoService.UsuarioDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPerfisAcoesPorCodigoPerfil", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPerfisAcoesPorCodigoPerfilRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisAcoesPorCodigoPerfilBusines" +
            "sFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisAcoesPorCodigoPerfilGeneral" +
            "FaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilAcaoOutputDto>> ListarPerfisAcoesPorCodigoPerfilAsync(string codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarPerfilAcao", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarPerfilAcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilAcaoBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilAcaoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarPerfilAcaoAsync(ControleAcessoService.PerfilAcaoDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilAcao", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirPerfilAcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilAcaoBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilAcaoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirPerfilAcaoAsync(ControleAcessoService.PerfilAcaoDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPerfisModulosPorCodigoPerfil", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPerfisModulosPorCodigoPerfilRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisModulosPorCodigoPerfilBusin" +
            "essFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPerfisModulosPorCodigoPerfilGener" +
            "alFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilModuloOutputDto>> ListarPerfisModulosPorCodigoPerfilAsync(string codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/SalvarPerfilModulo", ReplyAction="http://tempuri.org/IControleAcessoService/SalvarPerfilModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilModuloBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/SalvarPerfilModuloGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task SalvarPerfilModuloAsync(ControleAcessoService.PerfilModuloDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilModulo", ReplyAction="http://tempuri.org/IControleAcessoService/ExcluirPerfilModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilModuloBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ExcluirPerfilModuloGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task ExcluirPerfilModuloAsync(ControleAcessoService.PerfilModuloDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/EnviarSenha", ReplyAction="http://tempuri.org/IControleAcessoService/EnviarSenhaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/EnviarSenhaBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/EnviarSenhaGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task EnviarSenhaAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControleAcessoService/ListarPessoaPorCodigo", ReplyAction="http://tempuri.org/IControleAcessoService/ListarPessoaPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.BusinessFault), Action="http://tempuri.org/IControleAcessoService/ListarPessoaPorCodigoBusinessFaultFault" +
            "", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        [System.ServiceModel.FaultContractAttribute(typeof(ControleAcessoService.GeneralFault), Action="http://tempuri.org/IControleAcessoService/ListarPessoaPorCodigoGeneralFaultFault", Name="GeneralFault", Namespace="http://schemas.datacontract.org/2004/07/Coreon.Infra.ExceptionHandling")]
        System.Threading.Tasks.Task<ControleAcessoService.PessoaDto> ListarPessoaPorCodigoAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface IControleAcessoServiceChannel : ControleAcessoService.IControleAcessoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class ControleAcessoServiceClient : System.ServiceModel.ClientBase<ControleAcessoService.IControleAcessoService>, ControleAcessoService.IControleAcessoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ControleAcessoServiceClient() : 
                base(ControleAcessoServiceClient.GetDefaultBinding(), ControleAcessoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControleAcessoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ControleAcessoServiceClient.GetBindingForEndpoint(endpointConfiguration), ControleAcessoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControleAcessoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ControleAcessoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControleAcessoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ControleAcessoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControleAcessoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PessoaDto>> ListarPessoasAsync()
        {
            return base.Channel.ListarPessoasAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.SistemaOutputDto>> ListarSistemasAsync()
        {
            return base.Channel.ListarSistemasAsync();
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.SistemaOutputDto> ListarSistemaPorCodigoAsync(string codigo)
        {
            return base.Channel.ListarSistemaPorCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task SalvarSistemaAsync(ControleAcessoService.SistemaDto sistemaDto)
        {
            return base.Channel.SalvarSistemaAsync(sistemaDto);
        }
        
        public System.Threading.Tasks.Task ExcluirSistemaAsync(ControleAcessoService.SistemaDto sistemaDto)
        {
            return base.Channel.ExcluirSistemaAsync(sistemaDto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.DominioDto>> ListarDominioAsync(string dominio)
        {
            return base.Channel.ListarDominioAsync(dominio);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilOutputDto>> ListarPerfisAsync()
        {
            return base.Channel.ListarPerfisAsync();
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.PerfilOutputDto> ListarPerfilPorCodigoAsync(string codigo)
        {
            return base.Channel.ListarPerfilPorCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task SalvarPerfilAsync(ControleAcessoService.PerfilDto perfilDto)
        {
            return base.Channel.SalvarPerfilAsync(perfilDto);
        }
        
        public System.Threading.Tasks.Task ExcluirPerfilAsync(ControleAcessoService.PerfilDto perfilDto)
        {
            return base.Channel.ExcluirPerfilAsync(perfilDto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.AcaoOutputDto>> ListarPorCodigoSistemaCodigoModuloAsync(string codigoSistema, string codigoModulo)
        {
            return base.Channel.ListarPorCodigoSistemaCodigoModuloAsync(codigoSistema, codigoModulo);
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.AcaoOutputDto> ListarPorCodigoSistemaCodigoModuloCodigoAcaoAsync(string codigoSistema, string codigoModulo, string codigoAcao)
        {
            return base.Channel.ListarPorCodigoSistemaCodigoModuloCodigoAcaoAsync(codigoSistema, codigoModulo, codigoAcao);
        }
        
        public System.Threading.Tasks.Task SalvarAcaoAsync(ControleAcessoService.AcaoDto acaoDto)
        {
            return base.Channel.SalvarAcaoAsync(acaoDto);
        }
        
        public System.Threading.Tasks.Task ExcluirAcaoAsync(ControleAcessoService.AcaoDto acaoDto)
        {
            return base.Channel.ExcluirAcaoAsync(acaoDto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModulosAsync()
        {
            return base.Channel.ListarModulosAsync();
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.ModuloOutputDto> ListarModuloPorCodigoAsync(string codigo)
        {
            return base.Channel.ListarModuloPorCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModuloPorModuloAnteriorAsync(string codigo)
        {
            return base.Channel.ListarModuloPorModuloAnteriorAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.ModuloOutputDto>> ListarModulosPorPerfilAsync(string codigo)
        {
            return base.Channel.ListarModulosPorPerfilAsync(codigo);
        }
        
        public System.Threading.Tasks.Task SalvarModuloAsync(ControleAcessoService.ModuloDto dto)
        {
            return base.Channel.SalvarModuloAsync(dto);
        }
        
        public System.Threading.Tasks.Task ExcluirModuloAsync(ControleAcessoService.ModuloDto dto)
        {
            return base.Channel.ExcluirModuloAsync(dto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.UsuarioOutputDto>> ListarUsuariosAsync()
        {
            return base.Channel.ListarUsuariosAsync();
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorCodigoAsync(string codigo)
        {
            return base.Channel.ListarUsuarioPorCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorLoginAsync(string login)
        {
            return base.Channel.ListarUsuarioPorLoginAsync(login);
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.UsuarioOutputDto> ListarUsuarioPorEmailAsync(string email)
        {
            return base.Channel.ListarUsuarioPorEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task SalvarUsuarioAsync(ControleAcessoService.UsuarioDto dto)
        {
            return base.Channel.SalvarUsuarioAsync(dto);
        }
        
        public System.Threading.Tasks.Task ExcluirUsuarioAsync(ControleAcessoService.UsuarioDto dto)
        {
            return base.Channel.ExcluirUsuarioAsync(dto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilAcaoOutputDto>> ListarPerfisAcoesPorCodigoPerfilAsync(string codigoPerfil)
        {
            return base.Channel.ListarPerfisAcoesPorCodigoPerfilAsync(codigoPerfil);
        }
        
        public System.Threading.Tasks.Task SalvarPerfilAcaoAsync(ControleAcessoService.PerfilAcaoDto dto)
        {
            return base.Channel.SalvarPerfilAcaoAsync(dto);
        }
        
        public System.Threading.Tasks.Task ExcluirPerfilAcaoAsync(ControleAcessoService.PerfilAcaoDto dto)
        {
            return base.Channel.ExcluirPerfilAcaoAsync(dto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ControleAcessoService.PerfilModuloOutputDto>> ListarPerfisModulosPorCodigoPerfilAsync(string codigoPerfil)
        {
            return base.Channel.ListarPerfisModulosPorCodigoPerfilAsync(codigoPerfil);
        }
        
        public System.Threading.Tasks.Task SalvarPerfilModuloAsync(ControleAcessoService.PerfilModuloDto dto)
        {
            return base.Channel.SalvarPerfilModuloAsync(dto);
        }
        
        public System.Threading.Tasks.Task ExcluirPerfilModuloAsync(ControleAcessoService.PerfilModuloDto dto)
        {
            return base.Channel.ExcluirPerfilModuloAsync(dto);
        }
        
        public System.Threading.Tasks.Task EnviarSenhaAsync(string email)
        {
            return base.Channel.EnviarSenhaAsync(email);
        }
        
        public System.Threading.Tasks.Task<ControleAcessoService.PessoaDto> ListarPessoaPorCodigoAsync(string codigo)
        {
            return base.Channel.ListarPessoaPorCodigoAsync(codigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://core-e39.coreon.it/Coreon.ControleAcesso.WcfService/ControleAcessoService." +
                        "svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ControleAcessoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ControleAcessoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpEndpoint,
        }
    }
}
